contact/urls.py
from django.urls import path
from .views import index, single_contact, search, create, update, delete,register
from django.conf.urls.static import static
from django.conf import settings
app_name = 'contact'

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('contact/<int:contact_id>/detail/', single_contact, name='contact'),
    path('contact/create/', create, name='create'),
    path('contact/<int:contact_id>/update/', update, name='update'),
    path('contact/<int:contact_id>/delete/', delete, name='delete'),
    path('user/create', register, name='register')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(
        '',
        include('contact.urls')
    ),
    path(
        'admin/',
        admin.site.urls
    ),
]

contact/models.py
#type: ignore
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=45, verbose_name='Nome')
    last_name = models.CharField(
        max_length=45, verbose_name='Sobrenome', blank=True)
    phone = models.CharField(max_length=45, verbose_name='Telefone')
    email = models.EmailField(max_length=254)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True, verbose_name='Descrição')
    show = models.BooleanField(default=True)
    image = models.ImageField(upload_to='img/%Y/%m', blank=True,verbose_name='Imagem')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True, verbose_name='Categoria'
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
# type: ignore
from django import forms
from django.core.exceptions import ValidationError
from .models import Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class Form(forms.ModelForm):
    image = forms.ImageField(
        widget=forms.FileInput(attrs={'accept': 'image/*'},), required=False, label='Imagem')

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone',
                  'email', 'description', 'category', 'image')

    def clean(self):
        error_msg = ValidationError(
            'Primeiro nome não pode ser igual ao sobrenome', code='invalid')
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            self.add_error('first_name', error_msg)
            self.add_error('last_name', error_msg)
        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        return first_name


class OwnerForm(UserCreationForm):
    first_name = forms.CharField(required=True, label='Primeiro nome')
    last_name = forms.CharField(required=True, label='Sobrenome')
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',
                  'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error('email', ValidationError('Já existe esse email'))

        return email

contact/views/contact_forms.py
from django.contrib import messages
from contact.models import Contact
from contact.forms import Form
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse


def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = Form(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,

        }

        if form.is_valid():
            form.save()
            messages.success(request, 'Contato criado com sucesso')
            return redirect('contact:index')

        return render(
            request,
            'contact/create.html',
            context,
        )
    context = {
        'form': Form(),
        'form_action': form_action
    }
    return render(
        request,
        'contact/create.html',
        context,
    )


def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':

        form = Form(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,

        }

        if form.is_valid():

            contact = form.save()
            messages.success(request,"Contato atualizado com sucesso!")
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context,
        )

    context = {
        'form': Form(instance=contact),
        'form_action': form_action,
    }
    return render(
        request,
        'contact/create.html',
        context,
    )


def delete(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        messages.success(request, 'Contato apagado')
        return redirect('contact:index')

    return render(request, 'contact/single_contact.html', {'contact': contact, 'confirmation': confirmation, })

contact/views/user_forms.py
from email import message
from django.shortcuts import render, redirect
from contact.forms import OwnerForm
from django.contrib import messages


def register(request):
    form = OwnerForm()

    if request.method == 'POST':
        form = OwnerForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário criado com sucesso')
            return redirect('contact:index')

    return render(request, 'contact/register.html', {'form': form})

contact/views/viewns_contact.py
# type: ignore
from django.shortcuts import render
from contact.models import Contact
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator


def index(request):
    contacts = Contact.objects.all().filter(show=True).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'main_title': 'Contatos - ',
    }
    return render(
        request,
        'contact/index.html',
        context,
    )


def single_contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)

    context = {
        'contact': single_contact,
        'single_title': f'{single_contact.first_name} {single_contact.last_name} - '
    }

    return render(
        request,
        'contact/single_contact.html',
        context,
    )


def search(request):
    search_value = request.GET.get('q', '').strip().title()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects.all().filter(show=True).filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value)
    ).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    print(contacts.query)

    context = {
        'page_obj': page_obj,
        'main_title': 'Contatos - ',
    }
    return render(
        request,
        'contact/index.html',
        context,
    )

contact/templates/contact/create.html
{% include "partials/_head.html" %}
{% include "partials/_header.html" %}
  <div class="alert-center">
  {% for message in messages %}
    <div class="custom-alert {{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
</div>
<main class="content">
  <h2>Cadastro</h2>
  <div class="form_warper">
    <form action="{{form_action}}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form_content">
        {% for field in form %}
        <div class="form_group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{field}}
          {{field.errors}}
          {% if field.help_text %}
          <p class="help_text"></p>
          {% endif %}

            <div class="form_group">
            {% if field.name == 'image' and field.value.url %}
                <img src="{{field.value.url}}" alt="">
            </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
       {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}
      <div class="form_content">
        <div class="form_group">
          <button class="btn">
            Enviar
          </button>
        </div>
      </div>
    </form>
  </div>
</main>

contact/templates/contact/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    {% include "partials/_head.html" %}
  </head>
  <body>

  {% include "partials/_header.html" %}

  <div class="alert-center">
  {% for message in messages %}
    <div class="custom-alert {{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
</div>
    <main class="content">
      {% if page_obj %}
      <div class="responsive_table">
        <table class="contacts_table">
          <caption class="table_caption">
            Contatos
          </caption>
          <thead>
            <tr class="table_row table_row_reader">
              <th class="table_reader">ID</th>
              <th class="table_reader">Nome</th>
              <th class="table_reader">Sobrenome</th>
              <th class="table_reader">Telerone</th>
              <th class="table_reader">E-mail</th>
            </tr>
          </thead>
          <tbody>
            {% for contact in page_obj %}
            <tr class="table_row">
              <td class="table_cel">
                <a href="{% url "contact:contact" contact.id %}" class="table_link"> {{ contact.id }} </a>
              </td>
              <td class="table_cel">{{ contact.first_name }}</td>
              <td class="table_cel">{{ contact.last_name }}</td>
              <td class="table_cel">{{ contact.phone }}</td>
              <td class="table_cel">{{ contact.email }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}<h1 class="single_contact_name">
          Nenhum contato encontrado
        </h1>
      </div>
      {% endif %}
    </main>
    {% include "partials/_pagination.html" %}
    <script src="{% static "contact/js/scripts.js" %}"></script>
  </body>
</html>

contact/templates/contact/register.html
{% include "partials/_head.html" %}
{% include "partials/_header.html" %}

  <div class="alert-center">
  {% for message in messages %}
    <div class="custom-alert {{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
</div>
<main class="content">
  <h2>Cadastro</h2>
  <div class="form_warper">
    <form action="{{form_action}}" method="POST">
      {% csrf_token %}
      <div class="form_content">
        {% for field in form %}
        <div class="form_group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{field}}
          {{field.errors}}
          {% if field.help_text %}
          <p class="help_text">{{field.help_text}}</p>
          {% endif %}

        </div>
        {% endfor %}
      </div>
       {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}
      <div class="form_content">
        <div class="form_group">
          <button class="btn">
            Enviar
          </button>
        </div>
      </div>
    </form>
  </div>
</main>

contact/templates/contact/single_contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'contact/css/style.css' %}" />
    <title>{{single_title}}Agenda</title>
  </head>
  <body>

    {% include "partials/_header.html" %}

    <main class="content">
      <div class="single_contact">
        <h1 class="single_contact_name">
          {{contact.first_name}} {{contact.last_name}}
        </h1>
        <p><b>ID:</b>{{contact.id}}</p>
        <p><b>E-mail:</b>{{contact.email}}</p>
        <p><b>Phone:</b>{{contact.phone}}</p>
        <p><b>Created Date:</b>{{contact.created_date}}</p>
        <p><b>Description:</b>{{contact.description}}</p>
        <p><b>Category:</b>{{contact.category.name}}</p>

        {% if contact.image %}
            <p>
              <img src="{{contact.image.url}}" alt="{{contact.first_name}} {{contact.last_name}}">
            </p>
        {% endif %}
        <div class="contact_links">
          <a class = "btn btn_link"href="{% url "contact:update" contact.id %}">Editar</a>
        </div>
        <form action="{% url "contact:delete" contact.id %}" method = "POST">
          {% csrf_token %}

          {% if confirmation == 'no' %}
            <input type="hidden" name="confirmation" value="yes">
            <button class="btn btn-link" type="submit">Confirma?</button>
          {% else %}
            <button class="btn btn-link" type="submit">Deletar</button>
          {% endif %}
        </form>
      </div>
    </main>
  </body>
</html>

contact/templates/partials/_head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="{% static 'contact/css/style.css' %}" />
<title>{{main_title}}Agenda</title>

contact/templates/partials/_header.html
<header class="header">
      <h1 class="header_heading">
        <a href="{% url "contact:index" %}" class="header_link">
          Agenda
        </a>
        <div class="data">
          <p></p>
        </div>
      </h1>
      <nav class="nav_menu">
        <ul class="menu_list">
          <li class="menu_item">
            <a href="{% url "contact:create" %}" class="menu_link">Novo contato</a>
          </li>
          <li class="menu_item">
            <a href="" class="menu_link">2</a>
          </li>
      </nav>
      <div class="search">
        <form action="{% url "contact:search" %}" method="GET">
          <input type="text" class="search_input" placeholder="Busque" id="search" name="q" value="{{request.GET.q.strip}}">
        </form>
      </div>
    </header>

contact/templates/partials/_pagination.html
{% if page_obj %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1&q={{request.GET.q.strip}}">&laquo; Primeira</a>
    <a
      href="?page={{ page_obj.previous_page_number }}&q={{request.GET.q.strip}}"
      >Anterior</a
    >
    {% endif %}

    <span class="current">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}&q={{request.GET.q.strip}}"
      >Próxima</a
    >
    <a href="?page={{ page_obj.paginator.num_pages }}&q={{request.GET.q.strip}}"
      >última &raquo;</a
    >
    {% endif %}
  </span>
</div>
{% endif %}